custom build because https://github.com/softwaremill/github-actions-workflows/blob/main/.github/workflows/build-scala.yml doesn't support libcurl

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,25 +7,85 @@ on:
     tags: [v*]
 jobs:
   build:
-    uses: softwaremill/github-actions-workflows/.github/workflows/build-scala.yml@main
     # run on 1) push, 2) external PRs, 3) softwaremill-ci PRs
     # do not run on internal, non-steward PRs since those will be run by push to branch
     if: |
-      github.event_name == 'push' || 
+      github.event_name == 'push' ||
       github.event.pull_request.head.repo.full_name != github.repository ||
       github.event.pull_request.user.login == 'softwaremill-ci'
-    with:
-      java-version: '21'
-      compile-documentation: true
+    runs-on: ubuntu-24.04
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v6
+    - name: Set up JDK
+      uses: actions/setup-java@v5
+      with:
+        distribution: 'temurin'
+        java-version: '21'
+        cache: 'sbt'
+    - uses: sbt/setup-sbt@3e125ece5c3e5248e18da9ed8d2cce3d335ec8dd # v1, specifically v1.1.14
+    - name: Install libcurl
+      run: |
+        sudo apt-get update
+        sudo apt-get install libcurl3-dev
+    - name: Check formatting
+      run: sbt -v scalafmtCheckAll
+    - name: Compile
+      run: sbt -v compile
+    - name: Compile documentation
+      run: sbt -v compileDocumentation
+    - name: Test
+      run: sbt -v test
+    - uses: actions/upload-artifact@v5  # upload test results
+      if: success() || failure()        # run this step even if previous step failed
+      with:
+        name: 'tests-results-java-21'
+        path: '**/test-reports/TEST*.xml'
 
   publish:
-    uses: softwaremill/github-actions-workflows/.github/workflows/publish-release.yml@main
+    name: Publish release
     needs: [build]
     if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
-    secrets: inherit
-    with:
-      java-version: '21'
-      java-opts: "-Xmx4G"
+    runs-on: ubuntu-24.04
+    env:
+      JAVA_OPTS: "-Xmx4G"
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+      - name: Set up JDK
+        uses: actions/setup-java@v5
+        with:
+          distribution: 'temurin'
+          java-version: '21'
+          cache: 'sbt'
+      - uses: sbt/setup-sbt@3e125ece5c3e5248e18da9ed8d2cce3d335ec8dd # v1, specifically v1.1.14
+      - name: Install libcurl
+        run: |
+          sudo apt-get update
+          sudo apt-get install libcurl3-dev
+      - name: Compile
+        run: sbt compile
+      - name: Publish artifacts
+        run: sbt ci-release
+        env:
+          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
+          PGP_SECRET: ${{ secrets.PGP_SECRET }}
+          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
+          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
+      - name: Extract version from tag
+        run: |
+          version=${GITHUB_REF/refs\/tags\/v/}
+          echo "VERSION=$version" >> $GITHUB_ENV
+      - name: Publish release notes
+        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6, specifically v6.1.0
+        with:
+          config-name: release-drafter.yml
+          publish: true
+          name: "v${{ env.VERSION }}"
+          tag: "v${{ env.VERSION }}"
+          version: "v${{ env.VERSION }}"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   label:
     # only for PRs by softwaremill-ci
